### ISSUE TITLE
Homepage (index.html) Layout

### ISSUE THREAD

**Issue by Poolnudel** [Poolnudel/WebDev#2]
Create the homepage (index.html) with a header containing the 'WInf' logo, a full-width macro graphic, and a footer.
Acceptance Criteria:
- The homepage includes a header with the 'WInf' logo that has a shadow effect.
- A full-width macro graphic is present and darkened with a text overlay in Tea Green (#D7E4C0).
- Footer is present and extends across the entire page width, using Brunswick Green (#294936).
- The overall layout matches the minimalist style specified in the concept.

**Comment by Poolnudel** [comment]
- [x] 'WInf' logo ins Projekt laden

**Comment by cmuenzin** [comment]
![image](https://github.com/user-attachments/assets/b1b2c1b3-968f-4ab9-b35b-46d60ceb1e47)
