### ISSUE TITLE
Macro Graphic Scrolling Effect

### ISSUE THREAD

**Issue by Poolnudel** [Poolnudel/WebDev#3]
Add a scrolling effect on the macro graphic on the homepage, including a zoom effect.
Acceptance Criteria:
- On page load, the macro graphic displays the top 75% in the frame.
- Scrolling reveals the bottom 75% of the graphic.
- A smooth zoom effect reduces the graphic's width by 15% while scrolling.
- The text overlay on the graphic uses Tea Green (#D7E4C0) to ensure readability.

**Comment by Poolnudel** [comment]
@cmuenzin wie genau hast du dir das vorgestellt?

- [ ] Grafik für den bg im Projekt hochladen

**Comment by cmuenzin** [comment]
Suchste n Beispiel oder sprichst du bei vorstellen von Umsetzung im Code?

**Comment by Poolnudel** [comment]
suche schon ein Beispiel
ist das was du mir auf der Apple Seite gezeigt hast?
Hast du spontan noch weitere?
